### PR TITLE
Persistence of Classy Enum arrays

### PR DESCRIPTION
**Pull request by mgenereu**
Classy Enums support Enumerable and do cool things in array.
Classy Enums support cleanly persisting to a database.
Shouldn't Classy Enums support persisting an array of Classy Enums to a database?
Answer: Yes!  Put some chocolate in my peanut butter and some peanut butter in my chocolate!

### CODE REVIEW

**Comment by rhomeister** [comment]
I'd love to see this in ClassyEnum. I've actually hacked this together a couple of times myself for different projects. With a more principled solution that is part of this gem, I could throw away my code. (less code = happier rhomeister)

**Comment by beerlington** [comment]
@rhomeister I experimented with this a bit before releasing 4.0 but couldn't come up with an implementation that felt right in this library. I see the value of being able to select one or more values for a record and wanting them to be part of a known set, but I was having trouble justifying the fact that each value needed to be defined in its own class. The value of Classy Enum for me is being able to use polymorphism for an attribute, and reduce the amount of conditional logic spread across the application.

In your implementation, how are you using the array values once they are set on an object? Do you take advantage of each value being a class, or are you just using the values as strings? Understanding the use case a bit more would probably guide the implementation more.

I could also see maybe having a separate gem that handles array persistence, but it just doesn't feel like it's core to Classy Enum. Would you use a separate gem that depended on Classy Enum just for this?

**Comment by mgenereu** [comment]
I use it with select.  I'm half awake but it would look something like this.  A phone supports LTE if one of its Carrier attributes support LTE.

```ruby
class Phone
  def supports_lte?
    phone.carrier.select &:supports_lte?
  end
end
```

**Comment by beerlington** [comment]
@mgenereu thanks for the example, that makes sense. I will experiment with this a bit over the next week or two and see if I can come up with something that feels like a good fit. Aside from the current merge conflict, I don't like all the duplication between `classy_enum_array` and `classy_enum_attr`. I bet there is a way to get the desired functionality and still keep the Active Record logic in one place.

**Comment by beerlington** [comment]
It's been a while since this has seen any activity, so I'm going to close this. I plan to maintain this gem for a while with bug fixes, but don't think I'll be adding any new features.

**Pull request closed without merging**
